# Site settings
title: Web Friends
email: garthdb@webfriends.io
description: "A weekly interview show about the web and the friends who make it."
baseurl: "http://wwww.webfriends.io"
url: "http://webfriends.io"

# Build settings
markdown: kramdown
permalink: pretty
